### ISSUE TITLE
Asynchronous potions (Question | Enhancement)

### ISSUE THREAD

**Issue by ghost** [SuicidalKids/IonSpigot#1]
Hi, u can add asynchronous potions? i think that can be good for the performance.

**Comment by Samsuik** [comment]
I've done some work with potions to make them handle a lot better when the player or server is lagging with https://github.com/SuicidalKids/IonSpigot/commit/977187c2c4cbd96b0fbf589644a376b19d4f5930.

**Comment by ghost** [comment]
> I've done some work with potions to make them handle a lot better when the player or server is lagging with [977187c](https://github.com/SuicidalKids/IonSpigot/commit/977187c2c4cbd96b0fbf589644a376b19d4f5930).

sounds good
