### ISSUE TITLE
'Moved wrongly'

### ISSUE THREAD

**Issue by ghost** [SuicidalKids/IonSpigot#2]
Hi, i compiled IonSpigot 3 mins ago and started my test server (using IonSpigot), i sprinted and i got a setback, i see the console and shows this:

[20:31:09 WARN]: Lew_x moved wrongly!
[20:31:09 WARN]: Lew_x moved wrongly!
[20:31:09 WARN]: Lew_x moved wrongly!

---------------

Other info: 0 plugins, default configuration (no yml touched)
No changed code of IonSpigot
This issue doesn't happen in other forks like FlamePaper or SportPaper (same for original PaperSpigot)

**Comment by Samsuik** [comment]
This appears to be a bug with the movement cache and player movement. I just pushed commit https://github.com/SuicidalKids/IonSpigot/commit/ace3c05e8c107f54c0d053edeebdd57a73085d84 which should solve this issue.
