### ISSUE TITLE
Bad FlamePaper Feature

### ISSUE THREAD

**Issue by Ibramsou** [SuicidalKids/IonSpigot#6]
Please remove that from CraftChatMessage class:
![image](https://user-images.githubusercontent.com/62890758/117552718-78c3cb80-b04d-11eb-8abf-6d96cd6805df.png)

For example, with this feature, you can't read the full lines of a sign, and it can make issues with some plugins

**Comment by Samsuik** [comment]
This has nothing to do with IonSpigot. You should make an issue about this problem to them.

**Comment by Ibramsou** [comment]
Okay can  you read my other issue ? Thanks you
